projects:
  app:
    schemaPath: src/schema/app.graphql
    includes: [
      "app.graphql", 
      "prisma.graphql",
    ]
    extensions:
      endpoints:
        default: ${env:API_HOST}
  prisma:
    schemaPath: src/generated/schema/prisma.graphql
    includes: [
      "datamodel.prisma",
      "prisma.graphql", 
      "seed.graphql", 
      "bookingCreated.graphql"
    ]
    extensions:
      prisma: prisma/prisma.yml
      endpoints:
        default: ${env:PRISMA_HOST}
